name: VanishZ
main: Zaelee\Vanish
version: 1.0.0
api: 4.0.0
author: Zaelee

commands:
  vanish:
    description: "Go to Vanish"
    permission: vanish.use
  unvanish:
    description: "Remove Vanish"
    permission: vanish.use